name = "flygames"
main = "worker/index.ts"
compatibility_date = "2026-03-01"

[build]
command = "bash build.sh"

[[d1_databases]]
binding = "mysql"
database_name = "minecraft-wiki-db"
database_id = "83e4738d-6bb8-4ca3-7d90-e4c68b0ddfab"

[vars]
ENVIRONMENT = "production"
