name = "flygames"
main = "worker/index.ts"
compatibility_date = "2026-03-01"

[assets]
directory = "./dist"
binding = "ASSETS"

[[d1_databases]]
binding = "mysql"
database_name = "my-sql"
database_id = "d7f3eefe-63ff-4b62-8baf-6dc44381abab"

[vars]
ENVIRONMENT = "production"
